.\"
.TH ACMINFO 8 "2011-12-31" "tboot" "User Manuals"
.SH NAME
acminfo \- display the header info of a TXT ACM
.SH SYNOPSIS
.B acminfo
.I acm-file-name
.SH DESCRIPTION
.B acminfo
is used to display the header information for a TXT Authenticated Code Module (ACM) and match it with the current system.
.SH OPTIONS
.TP
.I acm-file-name
ACM file name
.SH EXAMPLES
\fBacminfo \fIi7_QUAD_SINIT_20.BIN
