.\"
.TH LCP_READPOL 8 "2011-12-31" "tboot" "User Manuals"
.SH NAME
lcp_readpol \- read the contents of an LCP policy index
.SH SYNOPSIS
.B lcp_readpol
.B \-i
.I index-value
.RB [\| \-f
.IR policy-file \|]
.RB [\|\-s
.IR size \|]
.RB [\|\-p
.IR passwd \|]
.RB [\| \-h \|]
.SH DESCRIPTION
.B lcp_readpol
is used to read the contents of an LCP policy index.  Any index can be specified but the output will be parsed as if it contained a policy.
.SH OPTIONS
.TP
.BI \-i\  index-value
Designate the index for reading. Index can be UINT32 or string. 3 strings
are supported for the reserved LCP indices. Strings and default index 
values for each string are:
.RS 
.IP default
0x50000001(INDEX_LCP_DEF)
.IP owner
0x40000001(INDEX_LCP_OWN)
.IP aux
0x50000002(INDEX_LCP_AUX)
.RE
.TP
.BI \-f\   policy-file
File name to write the policy data to. If no file name is specified then the contents will be displayed.
.TP
.BI \-s\   size
Value size to read from NV store. If no size inputted, read by length as
this index defined.
.TP
.BI \-p\  password
The TPM owner password
.TP
.B \-h
Print out the help message
.SH EXAMPLES
\fBlcp_readpol \-i \fIdefault \fB \-f \fIpolicy-file
.PP
\fBlcp_readpol \-i \fI0x00011101 \fB \-s \fI10
.PP
\fBlcp_readpol \-i \fI0x00011101 \fB \-f \fIpolicy-file \fB \-p \fI123456
.SH "SEE ALSO"
.BR lcp_writepol (8),
.BR lcp_crtpol (8).
